### ISSUE TITLE
Possible Use Cases

### ISSUE THREAD

**Issue by AndreasDane** [JDrapes/WEDA-MVC#10]
Provisional User:

Register with name/email and address using web service. 
Be given provisional password and login using it.

**Comment by AndreasDane** [comment]
Member:

Check outstanding balance
Make a payment
Submit a claim
List all claims/payments to date

**Comment by AndreasDane** [comment]
Admin:

List all members
List all oustanding balances
List all claims
List all provisional member applications
Process individual claims
Process membership applications and upgrade if payment is made
Suspend/resume membership
Report annual turnover

**Comment by AndreasDane** [comment]
A < role > < interacts in some way > with the < system > and the < system > < does something >

**Comment by JDrapes** [comment]
Thanks for these, I saw you put these on freed camp too :)
